```{r}
devtools::load_all(".")
library(climQMBC2)

var = 0
input = clim_Temp
e = list2env(input, .GlobalEnv)

pp_threshold = 1
pp_factor = 1e-2

l = formatQM(obs, mod, var)
```

```{r}
# l_org = climQMBC::formatQM(obs, mod, var, frq, pp_threshold, pp_factor)
```

## QM

```{r}
r = QM(obs, mod, var) %>% c()
r_org = climQMBC::QM(obs, mod, var, frq, pp_threshold, pp_factor) %>% c()
all.equal(r, r_org)
# plot(r, r_org)
```
## DQM

```{r}
r = map_DQM(obs, mod, var) %>% c()
r_org = climQMBC::DQM(obs, mod, var, frq, pp_threshold, pp_factor) %>% c()
all.equal(r, r_org)
```
## QQM

```{r}
r = map_QDM(obs, mod, var) %>% c()
r_org = climQMBC::QDM(obs, mod, var, frq, pp_threshold, pp_factor, rel_change_th = 2, inv_mod_th = pp_threshold) %>% c()
all.equal(r, r_org)
```
## UQM

```{r}
r = map_UQM(obs, mod, var) %>% c()
r_org = climQMBC::UQM(obs, mod, var) %>% c()
all.equal(r, r_org)
```

## SQM

```{r}
r = map_SDM(obs, mod, var) %>% c()
r_org = climQMBC::SDM(obs, mod, var) %>% c()
all.equal(r, r_org)
```
